### PR TITLE
[DO NOT MERGE] Migrate to Lerna

### PR DESCRIPTION
**Pull request by ryanlanciaux**
This is a work in progress branch of migrating the application to be use Lerna instead of one larger application.

### CODE REVIEW

**Comment by RyanCCollins** [comment]
Nice! This is great.  As soon as @StevenTCramer merges in his work, we can also merge in the ui-package work.  Have you seen that yet @ryanlanciaux?  It seems we are heading down the exact same path, so I want to make sure we land on the same spot.

**Comment by ryanlanciaux** [comment]
Yea! I accidentally opened this PR here instead of the Little Caesars fork initially :D The new one [exists here](https://github.com/littlecaesars/scalable-react-typescript-boilerplate/pull/2) and is just opened for visibility as I work through this. I have gone through an initial run through before @StevenTCramer's changes were in place but manually replaying these steps since the merge would be pretty rough :)

Agreed on ending up on the same place.

What I'm working on:

1. Add  `packages/UI` like you have in your lerna branch (including the Notification & Toast components).
2. Make `packages/demoapp` (which will be the default app that runs today). This will be set as the run target for the base package.json
3. Add a blank app that has it's own webpack.config + webpack.prod.config that people can use as the extension point of this code. 

When finished, the main directory will be pretty light -- mostly consisting of a package.json and some other config files / README / etc.

Thoughts on this?

**Comment by ryanlanciaux** [comment]
Or another possibility is maybe have the really barebones "starter" site live under the main `src` directory and `npm start` would run this.

`npm run demo` would run the demo app which lives under `packages/demoapp`.

**Comment by RyanCCollins** [comment]
Yes, that is exactly what I was thinking (combo of your last two comments.). I like it and can't wait to see how it turns out!

**Pull request closed without merging**
